name: Start SOCKS Access Pull Request from GH Issue
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'va.gov-team GitHub Issue Number'
        required: true
      access_type:
        description: 'config.yml key_group (developers, viewers, platform, etc)'
        required: true
        default: developers

env:
  GH_REPO_FOR_ISSUES: department-of-veterans-affairs/va.gov-team

jobs:
  gather_inputs:
    runs-on: ubuntu-latest
    outputs:
      email: ${{ fromJSON(steps.parse.outputs.payload)[' Your Email'] }}
      ssh_key: ${{ fromJSON(steps.parse.outputs.payload)[' Public SSH Key'] }}
      name: ${{ fromJSON(steps.parse.outputs.payload)[' Your Name'] }}
    steps:
      - name: Run Issue form parser
        id: parse
        uses: omgitsbillryan/issue-forms-body-parser@main
        with:
          issue_id: ${{ github.event.inputs.issue_number }}
          repository: ${{ env.GH_REPO_FOR_ISSUES }}
          separator: '###'
          label_marker_start: " "
          label_marker_end: "\n"
      - name: Debug
        run: echo "${{ steps.parse.outputs.payload }}"

  start_pull_request:
    runs-on: ubuntu-latest
    needs: gather_inputs
    if: |
      needs.gather_inputs.outputs.email != '' &&
      needs.gather_inputs.outputs.name != '' &&
      needs.gather_inputs.outputs.ssh_key != ''
    steps:
      - name: Get Token from Github App
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.GH_APP_PEM }}
          APP_ID: ${{ secrets.GH_APP_ID }}

      - name: Checkout The Github Repository
        uses: actions/checkout@v2
        with:
          token: ${{ steps.get_token.outputs.app_token }}

      # TODO - would be nice to alphabetize key name in YAML array
      - name: Update config.yml
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.key_groups.${{ env.type }} += ["${{ env.email }}"]' --inplace ansible/global/config.yml
        env:
          email: ${{ needs.gather_inputs.outputs.email }}
          type: ${{ github.event.inputs.access_type }}

      - name: Create /authorized_keys SSH Key File
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "ansible/roles/dsva-config/files/authorized_keys/${{ needs.gather_inputs.outputs.email }}"
          FILE_DATA: "${{ needs.gather_inputs.outputs.ssh_key }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          commit-message: New SOCKS ssh key
          branch: "socks-${{ needs.gather_inputs.outputs.email }}"
          title: "[Automated SOCKS Access] ${{ needs.gather_inputs.outputs.name }}"
          body: |
            An automated SOCKS Access Request

            - https://github.com/${{ env.GH_REPO_FOR_ISSUES }}/issues/${{ github.event.inputs.issue_number }}

            Triggered by: @${{ github.actor }} in [Job Run #${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: |
            automated-socks-request