name: Start SOCKS Access Pull Request
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue Number'
        required: true
        default: 9999
  # repository_dispatch:
  #   types: [start-socks-pr]

env:
  REPO: va.gov-team
  REO_OWNER: department-of-veterans-affairs

jobs:
  gather_inputs:
    runs-on: ubuntu-latest
    if: github.event.client_payload.issue_number != ''
    outputs:
      email: bill@aol.com # TODO
      type: 'developers' # TODO
      ssh_key: 'ssh-rsa ABCD1234 bill@aol.com' # TODO
    steps:
      - name: Run Issue form parser
        id: parse
        uses: omgitsbillryan/issue-forms-body-parser@659eb2c1b44efdbae04268844802f59924590396
        with:
          issue_id: #${{ github.event.client_payload.issue_number }}
          separator: '###'
          repository: department-of-veterans-affairs/va.gov-team
          label_marker_start: " "
          label_marker_end: "\\n"

      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"

  start_pull_request:
    runs-on: ubuntu-latest
    needs: gather_inputs
    if: |
      needs.gather_inputs.outputs.email != '' &&
      needs.gather_inputs.outputs.type != '' &&
      needs.gather_inputs.outputs.type != ''
    steps:
      - name: Checkout The Github Repository
        uses: actions/checkout@v2

  #     - name: Update config.yml
  #       uses: mikefarah/yq@master
  #       with:
  #         cmd: yq e '.key_groups.${{ env.type }} += ["${{ env.email }}"]' --inplace ansible/global/config.yml
  #       env:
  #         email: ${{ github.event.client_payload.email }}
  #         type: ${{ github.event.client_payload.type }}

  #     - name: Create /authorized_keys SSH Key File
  #       uses: "finnp/create-file-action@master"
  #       env:
  #         FILE_NAME: "ansible/roles/dsva-config/files/authorized_keys/${{ github.event.client_payload.email }}"
  #         FILE_DATA: "${{ github.event.client_payload.ssh_key }}"

  #     - name: Create Pull Request
  #       id: cpr
  #       uses: peter-evans/create-pull-request@v3
  #       with:
  #         token: ${{ steps.get_token.outputs.app_token }}
  #         commit-message: New SOCKS ssh key
  #         branch: "socks-${{ steps.split.outputs._0 }}"
  #         title: "[Automated SOCKS Access] ${{ steps.split.outputs._0 }}"
  #         body: |
  #           An automated SOCKS Access Request

  #           - ${{ github.event.issue.html_url }}

  #           Triggered by: @${{ github.event.comment.user.login }} in [this comment](${{ github.event.comment.html_url }})